name: LEMP Server
on:
  push:
    branches:
    - main
jobs:
  Build-App:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker Compose on the Runner
        run: |
         mkdir -p ~/.docker/cli-plugins/
         curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
         chmod +x ~/.docker/cli-plugins/docker-compose
         docker compose version
        
      - name: Build the Docker images
        run: docker compose build     #the command here was docker-compose build
        
      - name: Push the Docker Images to the Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker compose push

    
