name: LEMP Server
on:
  push:
    branches:
    - main
jobs:
  Build-App:
    runs-on: devopsclass
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker Compose on the Runner
        run: |
         mkdir -p ~/.docker/cli-plugins/
         curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
         chmod +x ~/.docker/cli-plugins/docker-compose
         docker compose version
        
      - name: Build the Docker images
        run: docker compose build     #the command here was docker-compose build
        
      - name: Push the Docker Images to the Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker compose push #it will now push the images

  Deploy-App:
    runs-on: devopsclass
    needs: Build-App
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH for the Deployment VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.228.26.159 >> ~/.ssh/known_hosts
          ssh -itt -oStrictHostKeyChecking=no ubuntu@34.228.26.159
          
      - name: Log in to Docker Hub to Pull Images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Start App
        run: |
          docker compose pull
          docker compose up -d
